// <auto-generated />
using System;
using APIPreExam.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIPreExam.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20181203130910_DataNotations")]
    partial class DataNotations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIPreExam.Models.AuctionItem", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BidCustomName")
                        .HasMaxLength(100);

                    b.Property<string>("BidCustomePhone")
                        .HasMaxLength(20);

                    b.Property<int>("BidPrice")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("BidTimeStamp");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(256);

                    b.Property<int>("ItemNumber")
                        .HasMaxLength(7);

                    b.Property<int>("RatingPrice");

                    b.HasKey("AuctionId");

                    b.ToTable("AuctionItems");
                });

            modelBuilder.Entity("APIPreExam.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CustomPhone")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("ItemNumber");

                    b.Property<int>("Price");

                    b.HasKey("BidId");

                    b.ToTable("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
